import { ConfigPlugin } from "@expo/config-plugins";
import { withStaticSettings } from "./static";
import {
  AnyPreferenceSpecifier,
  PSChildPaneSpecifier,
  SettingsPlist,
} from "./schema/SettingsPlist";
import {
  ChildPane,
  Group,
  RadioGroup,
  Slider,
  Switch,
  TextField,
  Title,
} from "./models";

// console.log(require('@expo/plist').default.parse(``))

// Replicates the CocoaPods Acknowledgements.plist format
function createAcknowledgementsPanel(
  licenses: { title: string; text: string }[] = []
): SettingsPlist {
  return {
    PreferenceSpecifiers: [
      Group({
        title: "Acknowledgements",
        footerText:
          "This application makes use of the following third party libraries:",
      }),
      ...licenses.map(({ title, text }) =>
        Group({
          title,
          footerText: text,
        })
      ),
      Group({
        title:
          "Generated by Expo Config Plugins - https://docs.expo.dev/config-plugins/introduction/",
      }),
    ],
  };
}

const AcknowledgementsPane: PSChildPaneSpecifier = {
  Type: "PSChildPaneSpecifier",
  Title: "Acknowledgements",
  File: "Acknowledgements",
};

function page(specs: AnyPreferenceSpecifier[]): { page: SettingsPlist } {
  return {
    page: {
      PreferenceSpecifiers: specs,
    },
  };
}

export const withSettingsBundle: ConfigPlugin = (config) => {
  return withStaticSettings(config, {
    Root: {
      locales: {
        en: {
          Name: "Bacon",
        },
        es: {
          Name: "El Baco",
        },
      },
      page: {
        PreferenceSpecifiers: [
          AcknowledgementsPane,
          Group({
            title: "Group",
          }),
          TextField({
            title: "Name",
            key: "name_preference",
            value: "",
            keyboardType: "Alphabet",
            autoCapitalize: "None",
            autoCorrect: "No",
          }),
          Switch({
            title: "Enabled",
            key: "enabled_preference",
            value: true,
          }),
          Slider({
            key: "slider_preference",
            value: 0.5,
          }),
          ChildPane({
            title: "About",
          }),
        ],
      },
    },
    About: page([
      Title({
        title: "About",
        key: "about",
        value: "This is a description of the app.",
      }),
      RadioGroup({
        value: "option1",
        key: "radio_preference",
        items: [
          {
            title: "Option 1",
            value: "option1",
          },

          {
            title: "Option 2",
            value: "option2",
          },
        ],
      }),
      ChildPane({
        title: "More",
      }),
    ]),
    More: page([
      Group({
        title: "Group",
        footerText: "This is a footer",
      }),
      ChildPane({
        title: "Acknowledgements",
      }),
    ]),
    Acknowledgements: {
      page: {
        ...createAcknowledgementsPanel([{ title: "blurhash", text: "foobar" }]),
      },
    },
  });
};
